workflows:
  ios-simulator-build:
    name: Build iOS app for Simulator (no signing)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build for iOS simulator
        script: |
          flutter build ios --simulator --release
    artifacts:
      - build/ios/iphonesimulator/**/*.app
