name: my_smart_alarm
description: Smart alarm app built with Flutter
publish_to: 'none'
version: 1.0.0+1  # обязательно для сборки

environment:
  sdk: '^3.9.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14

  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_native_timezone: ^2.0.0

  record: ^6.1.2
  just_audio: ^0.10.5

  permission_handler: ^12.0.1
  uuid: ^4.5.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/wake_tone.mp3
