platform :ios, '14.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Добавляем плагины Flutter вручную
  pod 'health', :path => '../.symlinks/plugins/health/ios'
  pod 'permission_handler', :path => '../.symlinks/plugins/permission_handler/ios'
  pod 'just_audio', :path => '../.symlinks/plugins/just_audio/ios'
  pod 'record', :path => '../.symlinks/plugins/record/ios'

end
